repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/pylint
    rev: "v2.15.6"
    hooks:
      - id: pylint
        name: Check for Linting errors on Python files
        description: This hook runs pylint.
        additional_dependencies:
          - urllib3
        types: [python]
        args:
          - -d duplicate-code
